# Monochrome colors for hyprlock
background {
    color = rgb(f5f5f5)
}

input-field {
    outline_thickness = 2
    outer_color = rgb(656565)
    inner_color = rgb(e5e5e5)
    font_color = rgb(252525)
    check_color = rgb(454545)
    fail_color = rgb(959595)
}

label {
    color = rgb(252525)
}
