# Monochrome light theme colors
set -g @SESSION_HIGHLIGHT "#454545"      # Hostname and session name color
set -g @WINDOW_ACTIVE_BG "#c5c5c5"       # Background for active window
set -g @WINDOW_ACTIVE_SEP "#101010"      # Separator color for active window
set -g @WINDOW_INACTIVE_SEP "#959595"    # Separator color for inactive windows
set -g @TEXT_MAIN "#252525"              # Main text color
