# Rose Pine Dawn theme for Yazi
# Based on: https://rosepinetheme.com

[flavor]
use = ""

[manager]
cwd = { fg = "#56949f" }

# Hovered
hovered         = { fg = "#faf4ed", bg = "#ea9d34" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#ea9d34", italic = true }
find_position = { fg = "#907aa9", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#286983", bg = "#286983" }
marker_copied   = { fg = "#ea9d34", bg = "#ea9d34" }
marker_cut      = { fg = "#b4637a", bg = "#b4637a" }

# Tab
tab_active   = { fg = "#faf4ed", bg = "#575279" }
tab_inactive = { fg = "#575279", bg = "#dfdad9" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#9893a5" }

# Highlighting
syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#dfdad9", bg = "#dfdad9" }

# Mode
mode_normal = { fg = "#faf4ed", bg = "#56949f", bold = true }
mode_select = { fg = "#faf4ed", bg = "#286983", bold = true }
mode_unset  = { fg = "#faf4ed", bg = "#b4637a", bold = true }

# Progress
progress_label  = { fg = "#575279", bold = true }
progress_normal = { fg = "#56949f", bg = "#dfdad9" }
progress_error  = { fg = "#b4637a", bg = "#dfdad9" }

# Permissions
permissions_t = { fg = "#286983" }
permissions_r = { fg = "#ea9d34" }
permissions_w = { fg = "#b4637a" }
permissions_x = { fg = "#d7827e" }
permissions_s = { fg = "#9893a5" }

[input]
border   = { fg = "#56949f" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#56949f" }
active   = { fg = "#907aa9" }
inactive = {}

[tasks]
border  = { fg = "#56949f" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#dfdad9" }
cand            = { fg = "#d7827e" }
rest            = { fg = "#9893a5" }
desc            = { fg = "#907aa9" }
separator       = "  "
separator_style = { fg = "#9893a5" }

[help]
on      = { fg = "#907aa9" }
exec    = { fg = "#d7827e" }
desc    = { fg = "#9893a5" }
hovered = { bg = "#9893a5", bold = true }
footer  = { fg = "#dfdad9", bg = "#575279" }

[filetype]
rules = [
	# Fallback
	{ name = "*", fg = "#575279" },
	{ name = "*/", fg = "#56949f" }
]
