# Zenbones Light colors for hyprlock
background {
    color = rgb(F0EDEC)
}

input-field {
    outline_thickness = 2
    outer_color = rgb(286486)
    inner_color = rgb(CBD9E3)
    font_color = rgb(2C363C)
    check_color = rgb(4F6C31)
    fail_color = rgb(A8334C)
}

label {
    color = rgb(2C363C)
}
