# Gruvbox Dark theme for Yazi
# Based on: https://github.com/morhetz/gruvbox

[flavor]
use = ""

[manager]
cwd = { fg = "#83a598" }

# Hovered
hovered         = { fg = "#282828", bg = "#fabd2f" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#fabd2f", italic = true }
find_position = { fg = "#d3869b", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#b8bb26", bg = "#b8bb26" }
marker_copied   = { fg = "#fabd2f", bg = "#fabd2f" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }

# Tab
tab_active   = { fg = "#282828", bg = "#ebdbb2" }
tab_inactive = { fg = "#ebdbb2", bg = "#3c3836" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#504945" }

# Highlighting
syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3c3836", bg = "#3c3836" }

# Mode
mode_normal = { fg = "#282828", bg = "#83a598", bold = true }
mode_select = { fg = "#282828", bg = "#b8bb26", bold = true }
mode_unset  = { fg = "#282828", bg = "#fb4934", bold = true }

# Progress
progress_label  = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#83a598", bg = "#3c3836" }
progress_error  = { fg = "#fb4934", bg = "#3c3836" }

# Permissions
permissions_t = { fg = "#b8bb26" }
permissions_r = { fg = "#fabd2f" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#8ec07c" }
permissions_s = { fg = "#928374" }

[input]
border   = { fg = "#83a598" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#83a598" }
active   = { fg = "#d3869b" }
inactive = {}

[tasks]
border  = { fg = "#83a598" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#3c3836" }
cand            = { fg = "#8ec07c" }
rest            = { fg = "#928374" }
desc            = { fg = "#d3869b" }
separator       = "  "
separator_style = { fg = "#504945" }

[help]
on      = { fg = "#d3869b" }
exec    = { fg = "#8ec07c" }
desc    = { fg = "#928374" }
hovered = { bg = "#504945", bold = true }
footer  = { fg = "#3c3836", bg = "#ebdbb2" }

[filetype]
rules = [
	{ name = "*", fg = "#ebdbb2" },
	{ name = "*/", fg = "#83a598" }
]
