# Catppuccin Latte theme for Yazi
# Based on: https://github.com/catppuccin/alacritty

[flavor]
use = ""

[manager]
cwd = { fg = "#1e66f5" }

# Hovered
hovered         = { fg = "#eff1f5", bg = "#df8e1d" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#df8e1d", italic = true }
find_position = { fg = "#ea76cb", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#40a02b", bg = "#40a02b" }
marker_copied   = { fg = "#df8e1d", bg = "#df8e1d" }
marker_cut      = { fg = "#d20f39", bg = "#d20f39" }

# Tab
tab_active   = { fg = "#eff1f5", bg = "#4c4f69" }
tab_inactive = { fg = "#4c4f69", bg = "#bcc0cc" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#acb0be" }

# Highlighting
syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#bcc0cc", bg = "#bcc0cc" }

# Mode
mode_normal = { fg = "#eff1f5", bg = "#1e66f5", bold = true }
mode_select = { fg = "#eff1f5", bg = "#40a02b", bold = true }
mode_unset  = { fg = "#eff1f5", bg = "#d20f39", bold = true }

# Progress
progress_label  = { fg = "#4c4f69", bold = true }
progress_normal = { fg = "#1e66f5", bg = "#bcc0cc" }
progress_error  = { fg = "#d20f39", bg = "#bcc0cc" }

# Permissions
permissions_t = { fg = "#40a02b" }
permissions_r = { fg = "#df8e1d" }
permissions_w = { fg = "#d20f39" }
permissions_x = { fg = "#179299" }
permissions_s = { fg = "#acb0be" }

[input]
border   = { fg = "#1e66f5" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#1e66f5" }
active   = { fg = "#ea76cb" }
inactive = {}

[tasks]
border  = { fg = "#1e66f5" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#bcc0cc" }
cand            = { fg = "#179299" }
rest            = { fg = "#acb0be" }
desc            = { fg = "#ea76cb" }
separator       = "  "
separator_style = { fg = "#acb0be" }

[help]
on      = { fg = "#ea76cb" }
exec    = { fg = "#179299" }
desc    = { fg = "#acb0be" }
hovered = { bg = "#acb0be", bold = true }
footer  = { fg = "#bcc0cc", bg = "#4c4f69" }

[filetype]
rules = [
	# Fallback
	{ name = "*", fg = "#4c4f69" },
	{ name = "*/", fg = "#1e66f5" }
]
