# Kanagawa Lotus colors for hyprlock
background {
    color = rgb(f2ecbc)
}

input-field {
    outline_thickness = 2
    outer_color = rgb(624c83)
    inner_color = rgb(e5ddb0)
    font_color = rgb(545464)
    check_color = rgb(6f894e)
    fail_color = rgb(c84053)
}

label {
    color = rgb(545464)
}
