# Monochrome colors for hyprlock
background {
    color = rgb(0a0a0a)
}

input-field {
    outline_thickness = 2
    outer_color = rgb(9a9a9a)
    inner_color = rgb(1a1a1a)
    font_color = rgb(dadada)
    check_color = rgb(bababa)
    fail_color = rgb(6a6a6a)
}

label {
    color = rgb(dadada)
}
