# Colors (Gruvbox Light)
# Source: https://github.com/morhetz/gruvbox

# Default colors
[colors.primary]
background = '#fbf1c7'
foreground = '#3c3836'

[colors.cursor]
text = '#fbf1c7'
cursor = '#3c3836'

[colors.vi_mode_cursor]
text = '#fbf1c7'
cursor = '#3c3836'

[colors.selection]
text = '#3c3836'
background = '#d5c4a1'

# Normal colors
[colors.normal]
black   = '#fbf1c7'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#7c6f64'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#9d0006'
green   = '#79740e'
yellow  = '#b57614'
blue    = '#076678'
magenta = '#8f3f71'
cyan    = '#427b58'
white   = '#3c3836'
