# Dracula theme for Yazi
# Based on: https://github.com/dracula/dracula-theme

[flavor]
use = ""

[mgr]
cwd = { fg = "#bd93f9" }

# Hovered
hovered         = { fg = "#282a36", bg = "#f1fa8c" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#f1fa8c", italic = true }
find_position = { fg = "#ff79c6", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#50fa7b", bg = "#50fa7b" }
marker_copied   = { fg = "#f1fa8c", bg = "#f1fa8c" }
marker_cut      = { fg = "#ff5555", bg = "#ff5555" }

# Tab
tab_active   = { fg = "#282a36", bg = "#f8f8f2" }
tab_inactive = { fg = "#f8f8f2", bg = "#44475a" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#6272a4" }

# Highlighting
syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#44475a", bg = "#44475a" }

# Mode
mode_normal = { fg = "#282a36", bg = "#bd93f9", bold = true }
mode_select = { fg = "#282a36", bg = "#50fa7b", bold = true }
mode_unset  = { fg = "#282a36", bg = "#ff5555", bold = true }

# Progress
progress_label  = { fg = "#f8f8f2", bold = true }
progress_normal = { fg = "#bd93f9", bg = "#44475a" }
progress_error  = { fg = "#ff5555", bg = "#44475a" }

# Permissions
permissions_t = { fg = "#50fa7b" }
permissions_r = { fg = "#f1fa8c" }
permissions_w = { fg = "#ff5555" }
permissions_x = { fg = "#8be9fd" }
permissions_s = { fg = "#6272a4" }

[input]
border   = { fg = "#bd93f9" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#bd93f9" }
active   = { fg = "#ff79c6" }
inactive = {}

[tasks]
border  = { fg = "#bd93f9" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#44475a" }
cand            = { fg = "#8be9fd" }
rest            = { fg = "#6272a4" }
desc            = { fg = "#ff79c6" }
separator       = "  "
separator_style = { fg = "#6272a4" }

[help]
on      = { fg = "#ff79c6" }
exec    = { fg = "#8be9fd" }
desc    = { fg = "#6272a4" }
hovered = { bg = "#6272a4", bold = true }
footer  = { fg = "#44475a", bg = "#f8f8f2" }

[filetype]
rules = [
	# Fallback
	{ name = "*", fg = "#f8f8f2" },
	{ name = "*/", fg = "#bd93f9" }
]
